version: '3.9'
services:
  db:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    networks:
      - app-net
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass12345
      MONGO_INITDB_DATABASE: wishlist
    volumes:
    - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

networks:
  app-net:
    driver: bridge

