FROM openjdk:17-jdk-slim

ENV SPRING_PROFILES_ACTIVE=dev
ENV MONGODB_HOST=localhost
ENV MONGODB_PORT=27017
ENV MONGODB_DATABASE=wishlist
ENV MONGODB_AUTHENTICATION_DATABASE=admin
ENV MONGODB_USERNAME=user
ENV MONGODB_PASSWORD=pass12345
ENV MONGODB_AUTO_INDEX_CREATION=true
ENV SPRINGDOC_VERSION=@springdoc.version@
ENV SPRINGDOC_API_DOCS_GROUPS_ENABLED=true
ENV SPRINGDOC_SWAGGER_UI_DISPLAY_REQUEST_DURATION=true
ENV SPRINGDOC_SWAGGER_UI_OPERATIONS_SORTER=alpha
ENV SPRINGDOC_SWAGGER_UI_DISABLE_SWAGGER_DEFAULT_URL=true
ENV SPRINGDOC_SWAGGER_UI_USE_ROOT_PATH=true

COPY target/*.jar wishlist.jar

ENTRYPOINT ["java", "-jar", "/wishlist.jar"]
