spring:
    data:
        mongodb:
            host: localhost
            port: 27017
            database: wishlist
            authentication-database: admin
            username: user
            password: pass12345
            auto-index-creation: true
springdoc:
    version: '@springdoc.version@'
    api-docs:
        groups:
            enabled: true
    swagger-ui:
        display-request-duration: true
        operationsSorter: alpha
        disable-swagger-default-url: true
        use-root-path: true